--- 
JB: 
  ASSET_PATH: false
  BASE_PATH: false
  analytics: 
    getclicky: 
      site_id: ~
    google: 
      tracking_id: UA-30908734-1
    mixpanel: 
      token: _MIXPANEL_TOKEN_
    provider: google
  archive_path: /archive.html
  atom_path: /atom.xml
  categories_path: /categories.html
  comments: 
    disqus: 
      short_name: kinghack
    facebook: 
      appid: 123
      colorscheme: light
      num_posts: 5
      width: 580
    intensedebate: 
      account: 123abc
    livefyre: 
      site_id: 123
    provider: disqus
  rss_path: /rss.xml
  sharing: 
    provider: false
  tags_path: /tags.html
  version: "0.3.0"
encoding: "utf-8"
markdown: kramdown
author: 
  email: ilsh1022@gmail.com
  feedburner: "http://feed.feedburner.com/github/VbZg"
  github: Kinghack
  name: happyface
  twitter: happyface1022
exclude: 
  - vendor
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md
highlighter: rouge
permalink: !ruby/symbol "day/:month/:year/:title"
production_url: "http://Kinghack.github.com"
tagline: ~
title: zichai

