permalink: :day/:month/:year/:title 

exclude: ["vendor", ".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
#auto: true
highlighter: "rouge"

title: 子柴
tagline: 
author:
  name: happyface
  email: ilsh1022@gmail.com
  github: Kinghack
  twitter: happyface1022
  feedburner: http://feed.feedburner.com/github/VbZg

production_url: http://Kinghack.github.com

JB:
  version: 0.3.0

  BASE_PATH : false 

  ASSET_PATH: false

  archive_path: /archive.html
  categories_path: /categories.html
  tags_path: /tags.html
  atom_path: /atom.xml
  rss_path: /rss.xml

  comments:
    provider: disqus
    disqus:
      short_name: kinghack
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 123
      num_posts: 5
      width: 580
      colorscheme: light
   
  analytics:
    provider: google 
    google: 
        tracking_id: 'UA-30908734-1'
    getclicky:
      site_id: 
    mixpanel:
        token: '_MIXPANEL_TOKEN_'

  sharing:
    provider: false
    
